version: "3.8"

services:
  app:
    container_name: dd-ai-center
    image: dd-ai-center
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # Map React dev server's port
    volumes:
      - .:/app # Mount the current directory into the container
      - /app/node_modules # Avoid overwriting node_modules with an empty folder
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes

